version: '3'

services:
  postgres:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=go_authentication
    hostname: postgres
  
  app:
    image: go_authentication:latest
    hostname: app
    ports:
      - 3000:3000
    depends_on:
      - postgres
